### ISSUE TITLE
EmbeddedCanvas.update()

### ISSUE THREAD

**Issue by forcar** [gavalian/groot#20]
Recent change of EmbeddedCanvas.update():

		JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
 		topFrame.getContentPane().setVisible(false);
                this.repaint();   
 		topFrame.getContentPane().setVisible(true);

causes my various TextEntry fields in the topFrame to stop working if Timer if firing off repeated updates to refresh the canvas.  I can always replace canvas.update() with canvas.repaint() to prevent this, but the above code doesn't look like something we want this class to do.

**Comment by wphelps** [comment]
Sometimes GUIs update faster if you don't draw every update to the screen and wait to update everything all at once, this  was a leftover from that test!  It didn't help much. I went ahead and updated the jar and removed those lines.
