### ISSUE TITLE
Refreshing a canvas

### ISSUE THREAD

**Issue by naharrison** [gavalian/groot#31]
@wphelps @gavalian I've notice that my canvases are often drawn initially with some ugly overlaps/cropping, but when I drag the corner of the window it refreshes and then looks fine. Do you know why this is? I attached some before/after images to show the point.

Before:

![image](https://cloud.githubusercontent.com/assets/20796892/25285606/dec5669e-2688-11e7-8e4f-f3c00a8e796d.png)

After:

![image](https://cloud.githubusercontent.com/assets/20796892/25285662/0f9dc1da-2689-11e7-87a2-1210e4e9b45e.png)

**Comment by wphelps** [comment]
@gavalian. Is this resolved? I thought you fixed this a while back.

**Comment by gavalian** [comment]
I think this was fixed.
