### ISSUE TITLE
missing axis min/max

### ISSUE THREAD

**Issue by naharrison** [gavalian/groot#33]
@wphelps @gavalian Sometimes axes have no min and max values:

![screen shot 2017-05-05 at 3 44 35 pm](https://cloud.githubusercontent.com/assets/20796892/25761715/d1137190-31a9-11e7-9e89-a37400a18d6d.png)

**Comment by wphelps** [comment]
That's a pretty narrow plot. Do the axis labels appear after changing the aspect ratio to a more landscape orientation?

**Comment by naharrison** [comment]
Yes, if you drag the corner of the window to widen it, the problem gets fixed. Also note the duplicate labels in the stat box!

**Comment by wphelps** [comment]
Check to see how many datasets are in your canvas. Most likely there are two datasets.

**Comment by wphelps** [comment]
The fitter automatically draws the function, so there's no need to draw it again. That's the way @gagik designed it.
