### ISSUE TITLE
Data Graph Plotting Draw Options

### ISSUE THREAD

**Issue by lucillalanza** [gavalian/groot#43]
Hi,

can you please add an option to link points of a GraphErrors with lines?

Thank you in advance

**Comment by wphelps** [comment]
Hey Lucilla,

I added it as a an draw option "L" in the commit 58cbbb79550961781671be09143c2a364db2015d.
Gagik will update the maven repository and it will end up in the coatjava build when FX updates it.

-Will

**Comment by lucillalanza** [comment]
Hi Will,

thank you very much for your quick reply. So, if I understood correctly, I
have to wait the updated coatjava build to download the new jar and use it
for my algorithm. Is it correct?

2017-11-28 1:42 GMT+01:00 Will Phelps <notifications@github.com>:

**Comment by gavalian** [comment]
The repository is updated, the new groot-2.0 has the changes included.

Gagik
