### ISSUE TITLE
Directory and DataSet disappears when saving histograms to hipo file

### ISSUE THREAD

**Issue by Guillaum-C** [gavalian/groot#44]
When trying to save histograms into a hipo file, one of them (and its directory) always disappears (the first directory created).

Minimal example:
(tested with coat-lib 4.0 from coatjava 5a13 and tested with coat-lib 5.1 from coatjava master on February 16)
```
TDirectory dir = new TDirectory();
H1F h1 = this.get1DHisto(plotName);
dir.mkdir("/calibration/PCAL");
dir.mkdir("/calibration/ECIN");

dir.cd("/calibration/ECIN");
dir.addDataSet(h1);
dir.cd("/calibration/PCAL");
dir.addDataSet(h1);
        
dir.writeFile("testfile.hipo");
        
TDirectory diread = new TDirectory();
diread.readFile("testfile.hipo");
diread.cd();
diread.ls();
```

**Comment by gavalian** [comment]
This issue was related to HIPO not reading first event, it has been resolved.
