### ISSUE TITLE
Move to JeffersonLab github?

### ISSUE THREAD

**Issue by tylern4** [gavalian/groot#46]
If this is supposed to be the "official" repository for the groot, used by the clas12-offline-software, it should be moved over to the jeffersonlab github so it can be worked on by everyone.

**Comment by wphelps** [comment]
I think it was intended to be a separate project from CLAS/CLAS12 since it was more general than just CLAS/CLAS12 interests and since then several other projects/users have taken interest outside of the lab. It can be worked on by everyone, just submit a pull request and Gagik or I will approve it.

**Comment by gavalian** [comment]
GROOT is for general purpose, and it is intended for much wider use than Jefferson Lab and Class 12.
This one, unlike clas12tools repository, will not be moved to Jefferson Lab.
