### ISSUE TITLE
some H2F plotting features

### ISSUE THREAD

**Issue by afilippi67** [gavalian/groot#68]
Hello, I was wondering whether you could add a few plotting features for 2D histograms (no hurry) - what I'd like to plot are 2D simple 2D histograms by markers (not by the usual color scale), so to study the distribution of points and eventually compare several distributions superimposing more plots with different markers. It would be nice to be able to set a marker style, and select a color for each histogram. 
It could also be helpful to plot the H2F object as "box" (which is already possible), but selecting a different color per histogram so to allow, again, a visually meaningful superimposition (I don't think this is possible as of now for H2Fs).
Thanks!

**Comment by gavalian** [comment]
The BOX, option does allow you to select Line color which is bee used to draw boxes. You can
overlay histograms. 
Marker plotting is not implemented yet, but can be done.

**Comment by afilippi67** [comment]
ok thanks, as for the box option I'll look better into it (I expected something similar to a TH2F::SetLineColor root method, but I wasn't able to find it, my bad).

**Comment by gavalian** [comment]
Here is an image of root DEMO showing possible 2D histograms plotting styles.
![Plot_03-01-2021_08 01 27_AM](https://user-images.githubusercontent.com/7406678/109500808-b8c26d00-7a64-11eb-91ba-f2ea5184d013.png)

**Comment by afilippi67** [comment]
Perfect, that's exactly what I needed!
Thanks.
