### ISSUE TITLE
Saving H1F n. entries, overflow and underflow

### ISSUE THREAD

**Issue by raffaelladevita** [gavalian/groot#69]
It would be useful to have H1F parameters such as number of entries, overflows and underflows saved when histograms are saved to a file

**Comment by gavalian** [comment]
I have started working on porting histogram I/O to HIPO-4. I will introduce this feature.

**Comment by wphelps** [comment]
This also applies to text files. @AndruQuiroga can you add this feature for H1Fs and H2Fs?

**Comment by gavalian** [comment]
This feature is already implemented in 4.1 version, it only works with HIPO-4 export.
